name: Update README

on:
  push:
    branches:
      - main  # Adjust this based on your default branch

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Visitor's Username
        run: echo "VISITOR_USERNAME=${GITHUB_ACTOR}" >> $GITHUB_ENV

      - name: Update README
        run: node .github/scripts/update-readme.js
